_target_: locodiff.jit_agent.JitAgent
_recursive_: false

num_sampling_steps: ${n_timesteps}
sigma_data: ${sigma_data}
sigma_min: 0.001
sigma_max: 80
device: ${device}

obs_dim: ${obs_dim}
action_dim: ${action_dim}
T: ${T}
T_cond: ${T_cond}
T_action: ${T_action}
cond_lambda: ${cond_lambda}

model:
  _target_: locodiff.wrapper.ScalingWrapper
  _recursive_: false

  sigma_data: ${sigma_data}

  inner_model:
    _target_: locodiff.transformer.DiffusionTransformer
    obs_dim: ${obs_dim}
    skill_dim: ${skill_dim}
    act_dim: ${action_dim}
    d_model: ${hidden_dim}
    nhead: ${n_heads}
    num_layers: ${num_hidden_layers}
    T: ${T}
    T_cond: ${T_cond}
    device: ${device}
    cond_mask_prob: ${cond_mask_prob}
    dropout: ${dropout}

dataset_fn:
  _target_: locodiff.dataloader.get_dataloaders_and_scaler
  data_directory: ${data_path}
  obs_dim: ${obs_dim}
  train_fraction: 0.95
  device: ${device}
  T_cond: ${T_cond}
  T: ${T}
  train_batch_size: 1024
  test_batch_size: 1024
  num_workers: 4
  return_horizon: ${reward_horizon}
  reward_fn: ${reward_fn}
  scaling: ${scaling}
