_target_: locodiff.transformer.DiffusionTransformer
obs_dim: ${obs_dim}
skill_dim: ${skill_dim}
act_dim: ${action_dim}
d_model: 1024
nhead: 16
num_layers: 6
T: ${T}
T_cond: ${T_cond}
device: ${device}
cond_mask_prob: ${cond_mask_prob}
dropout: 0.0
weight_decay: 1e-3
