_target_: locodiff.transformer.DiffusionTransformer
obs_dim: ${obs_dim}
skill_dim: ${skill_dim}
act_dim: ${action_dim}
d_model: 128
nhead: 4
num_layers: 2
T: ${T}
T_cond: ${T_cond}
device: ${device}
cond_mask_prob: ${cond_mask_prob}
dropout: 0.0
weight_decay: 1e-3
