_target_: locodiff.classifier_workspace.ClassifierWorkspace

wandb_project: locodiff_classifier
wandb_mode: online

# training
train_steps: 5e5
eval_every: 1000
seed: 6
device: cuda

#dims
obs_dim: 33
action_dim: 12
skill_dim: 2
T: 4
T_cond: 8
T_action: 1
num_envs: 125

# diffusion
sampling_steps: 3
sigma_data: 0.5
sigma_min: 0.001
sigma_max: 80

# reward
return_horizon: 50
reward_fn: fwd_bwd

classifier:
  _target_: locodiff.classifier.ClassifierTransformer
  obs_dim: ${obs_dim}
  skill_dim: ${skill_dim}
  act_dim: ${action_dim}
  d_model: 128
  nhead: 4
  num_layers: 2
  T: ${T}
  T_cond: ${T_cond}
  device: ${device}
  dropout: 0.0
  weight_decay: 1e-3

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  betas: [0.9, 0.999]

lr_scheduler:
  _partial_: true
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train_steps}

dataset_fn:
  _target_: locodiff.dataloader.get_dataloaders_and_scaler
  data_directory: walk_rand
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  train_fraction: 0.95
  device: ${device}
  T_cond: ${T_cond}
  T: ${T}
  train_batch_size: 1024
  test_batch_size: 1024
  num_workers: 4
  return_horizon: ${return_horizon}
  reward_fn: ${reward_fn}
  scaling: linear
  evaluating: false

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
