defaults:
  - agents: agent
  - _self_

data_path: walk_torque

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb:
  entity: reeceomahoney
  project: locodiff

# general params
device: cuda
seed: 6
T: 4
T_cond: 8
T_action: 1

action_dim: 12
obs_dim: 33
skill_dim: 2

# policy model params
hidden_dim: 256
num_hidden_layers: 4
weight_decay: 1e-3
train_method: "steps"
max_train_steps: 1e6
max_epochs: 100
eval_every_n_steps: 1000
sim_every_n_steps: 5000

# BESO hyperparameters
dropout: 0.0
n_heads: 4
use_ema: True
decay: 0.999
update_ema_every_n_steps: 1
sigma_data: 0.2
cond_mask_prob: 0.1
cond_lambda: 1
n_timesteps: 3

env:
  render: True
  num_envs: 30
  num_threads: "auto"
  simulation_dt: 0.005
  control_dt: 0.04
  max_time: 10000
  enable_dynamics_randomization: False
  action_scaling: 1.0
  use_actuator_network: True
  server_port: 8080
  early_termination: True
  normalize_observation: False
  eval_n_times: 1
  eval_n_steps: 250

  velocity_command:
    limit_heading_velocity: 0.8
    limit_lateral_velocity: 0.5
    limit_yaw_rate: 1.0

    # Less than this is considered to be a zero velocity command
    limit_velocity_magnitude: 0.1

    # These values are rescaled if their sum is not equal to 1
    probability_zero_command: 0.2
    probability_heading_command: 0.0
    probability_lateral_command: 0.0
    probability_yaw_command: 0.0
    probability_direction_command: 0.0
    probability_constant_command: 0.8 # includes all three velocities

    # Time range in seconds when the next command is sampled
    command_sampling_time_min: 3.0
    command_sampling_time_max: 4.0
