program: scripts/training.py
project: locodiff
name: sweep
method: bayes
metric:
  goal: maximize
  name: max_reward_mean
parameters:
  train_steps:
    value: 1e5
  T:
    values: [1, 2, 4, 8, 16, 32]
  T_cond:
    values: [1, 2, 4, 8, 16, 32]
  sigma_data:
    values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  cond_mask_prob:
    values: [0.1, 0.2, 0.25]
  return_horizon:
    values: [10, 20, 50, 100]
  agent.sigma_min:
    values: [0.001, 0.005, 0.4]
  agent.sigma_max:
    values: [1, 40, 80]
  agent.model.model.d_model:
    values: [128, 256, 512]
  agent.model.model.num_layers:
    values: [2, 4, 6]
  agent.model.model.nhead:
    values: [2, 4, 8, 16]
  agent.model.model.dropout:
    values: [0.0, 0.05, 0.1, 0.2, 0.3]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

